---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  nfs:
    path: /mnt/nfsshare/grafana
    server: 192.168.0.160

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nfs-pvc
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
  labels:
    app: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: server
        url: http://192.168.0.112:9090
        version: 1
        editable: true

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: grafana


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        envFrom:
        - configMapRef:
            name: grafana-configmap
        volumeMounts:

        - mountPath: /var/lib/grafana
          name: grafana-pv
#        - mountPath: /etc/grafana
#          name: grafana-ge-config
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-nfs-pvc
        # - name: grafana-ge-config
        #   configMap:
        #     name: grafana-configmap
